<a href="https://colab.research.google.com/github/Harry1402/Neural_network_from_scratch/blob/main/Neural_Network8_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install nnfs
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
    self.weights =0.10 * np.random.randn(n_inputs ,n_neurons) #(rows,colums)
    self.biases=np.zeros((1,n_neurons))

  def forward(self ,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases


class Activation_Relu:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)

class Activation_softmax:
  def forward(self,inputs):
    exp_values = np.exp(inputs - np.max(inputs ,axis=1 ,keepdims=True))
    probabilitiies =exp_values/np.sum(exp_values,axis=1,keepdims=True)
    self.output=probabilitiies

class Loss:
  def calculate(self,output,y):
    raise NotImplementedError("Subclasses must implement calculate method")

class Loss_CategoricalCrossentropy(Loss):
  def calculate(self,y_pred,y_true):
    samples =len(y_pred)
    y_pred_clipped =np.clip(y_pred,1e-7, 1 - 1e-7)

    if len(y_true.shape)==1:
      correct_confidences=y_pred_clipped[range(samples),y_true]
    elif len(y_true.shape)==2:
      correct_confidences=np.sum(y_pred_clipped*y_true,axis=1)
    negative_log_likelihoods = -np.log(correct_confidences)
    return np.mean(negative_log_likelihoods)


x,y =spiral_data(samples=100 ,classes=3)

dense1=Layer_Dense(2,3)
activation1 =Activation_Relu()

dense2=Layer_Dense(3,3)
activation2 =Activation_softmax()

dense1.forward(x)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

loss_function=Loss_CategoricalCrossentropy()
loss=loss_function.calculate(activation2.output,y)

print(f"Loss: {loss}")

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]
Loss: 1.0984450578689575
