<a href="https://colab.research.google.com/github/Harry1402/Neural_network_from_scratch/blob/main/NeuralNetwork_3_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
inputs = [1,2,3,4,5];
weights =[[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,0.27,0.17,0.87],[-0.26,0.27,0.17,0.87]];
biases =[2,3,4,0.5];


outputwaa=[];

for ek_neuron_ka_weigghts ,ek_neuron_ka_biases in zip(weights,biases):
  ek_neuron_ka_output=0;

  for n_input ,weight in zip(inputs, ek_neuron_ka_weigghts):
    ek_neuron_ka_output = ek_neuron_ka_output+ n_input * weight

    ek_neuron_ka_output =ek_neuron_ka_output+ ek_neuron_ka_biases;

  outputwaa.append(ek_neuron_ka_output);

  print(outputwaa);




[12.3]
[12.3, 9.46]
[12.3, 9.46, 20.27]
[12.3, 9.46, 20.27, 6.27]


In [ ]:
import numpy as np;

inputs=[[2,3,4,5],
        [3,4,5,6],
         [2,3,4,5]];

weights=[[32,43,4,5],
        [3,4,55,6],
         [2,63,4,65]];

inputs2=[[2,3,4,5],
        [3,4,5,6],
         [2,3,4,5]];

weights2=[[32,43,4],
        [3,4,55],
         [2,63,4]];

biases =[2,3,4]; # Changed from [2,3,4,5] to [2,3,4]

biases2 =[2,3,4];

layer_outputs1=np.dot(inputs,np.array(weights).T )+biases;

layer_outputs2=np.dot(layer_outputs1,np.array(weights2).T )+biases2;
print(layer_outputs2)

[[21359 31385 19701]
 [27507 39279 24689]
 [21359 31385 19701]]
