<a href="https://colab.research.google.com/github/Harry1402/Neural_network_from_scratch/blob/main/Neural_network4_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np ;

X=[[2,3,4,5],
   [3,4,5,6],
   [2,3,4,5]]; # (3,4)

class Layer_Dense:
  def __init__(self,n_inputswa,n_neuronswa):
    self.weights =0.10 * np.random.randn(n_inputswa ,n_neuronswa) #(rows,colums)
    self.biases=np.zeros((1,n_neuronswa))
  def forward(self ,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)
layer3 =Layer_Dense(2,5)

layer1.forward(X)
layer2.forward(layer1.output) # Call the forward method to compute the output
layer3.forward(layer2.output)
print(layer3.output);

[[ 0.00478889  0.00137015 -0.01492231 -0.00970152  0.00492541]
 [ 0.00758219  0.00202024 -0.0193581  -0.01058048  0.00740732]
 [ 0.00478889  0.00137015 -0.01492231 -0.00970152  0.00492541]]


In [ ]:
# import numpy as np ;

# inputs=[[2,3,4,5],
#         [3,4,5,6],
#         [2,3,4,5]];

# weights =[[2,3,4,5],
#           [3,4,5,6],
#           [2,3,4,5]];

# biases= [2,3,4]


# weights2 =[[2,3,4],
#           [3,4,5],
#           [2,3,4]];

# biases2= [2,3,4]

# layer1_outtput = np.dot(inputs ,np.array(weights).T)+biases
# layer2_output =np.dot(layer1_outtput ,np.array(weights2).T)+biases2

# outtput = np.array(layer2_output)

# print(outtput);

[[559 745 561]
 [697 929 699]
 [559 745 561]]
